### ISSUE TITLE
Support for Devuan Linux

### ISSUE THREAD

**Issue by QuadPiece** [NIXStats/nixstatsagent#25]
Currently you cannot install the nixstatsagent on a Devuan Linux machine using the wget commands provided by nixstats.com's "Add Server" button. It will throw an error with a list of supported distros.

Devuan Linux ([devuan.org](https://devuan.org/)) is a fork of Debian that aims to act as an replacement for people who do not agree with Debian's inclusion of systemd.

If possible, I believe Devuan support should be added because:
1. It is a distro garnering increasing amounts of attention (Being ranked 36 on Distrowatch right now)
2. As of now it is mostly identical to Debian except for the init system, so it should be relatively easy to add support

**Comment by vfuse** [comment]
Considering you have python 2.7 and python-pip installed you can install the agent like this:

`pip install nixstatsagent`

Create a system service (/etc/init.d/nixstatsagent) https://gist.github.com/vfuse/6940a4a2353d285e7837cc6b8120111e

Once you have the nixstatsagent installed you can run:

`nixstatshello userid /etc/nixstats-token.ini` to create a serverid

You can find your userid on the servers page when click "add server".

After that restart the agent `service nixstatsagent restart`

**Comment by QuadPiece** [comment]
Thank you, that init script was of great help.

I do still think Devuan or another systemd-less distro should be considered for "official" support however. But I guess that's more of an issue for the site's setup script than it is for the agent.

Currently there is no officially recommended distro without systemd (Unless you count older releases such as CentOS 6 and Debian 7, which will eventually be deprecated). Just a little thing to consider for the roadmap, doesn't have to be Devuan, stuff like Gentoo is also popular.
