### ISSUE TITLE
RHEL 8 support

### ISSUE THREAD

**Issue by idnovic** [NIXStats/nixstatsagent#34]
I wanted to install nixstatsagent on rhel 8 beta.
I was not able to use your guide but downloaded the .sh file and made changes.
You can view it here
https://github.com/idnovic/nixstatsagent/blob/master/nixstatsagent.sh

It is just a quick fix. You can diff the file with your version to look for the changes I needed to make to support rhel 8. As far as I remember I swapped wget for curl because wget is not in any repo for rhel 8 right now. Maybe I edited other parts too, dunno.

Thank you

**Comment by damianperera** [comment]
This still doesn't support RHEL 8 although it was released on September 24th, 2019.

Fails with the below errors when attempting to install on CentOS 8.1:
```
nixstatsagent.sh: line 1061: nixstatshello: command not found
which: no nixstatsagent in (/sbin:/bin:/usr/sbin:/usr/bin)
```
