### ISSUE TITLE
Which ports should be open?

### ISSUE THREAD

**Issue by mthld** [NIXStats/nixstatsagent#36]
Hi,

I would like to know which ports needs to be kept open, I want to properly setup the firewall on my server.

Thanks in advance,

**Comment by vfuse** [comment]
port 443 (https) to api.nixstats.com

**Comment by mthld** [comment]
Thanks for answering,

> port 443 (https) to api.nixstats.com

ICMP requests (incoming pings) should be allowed as well right?
