### ISSUE TITLE
Feature request: opt-out network interfaces

### ISSUE THREAD

**Issue by mthld** [NIXStats/nixstatsagent#39]
Hi,

It would be cool to be able to opt-out the monitoring of some network interfaces.
As we are using virtualised and para-virtualised systems, there is a lot of virtual interfaces running and they are making a lot of noise on the graphs.

If we can specify that we don't want some to be checked in `nixstats.ini` it would be perfect:
```
[network]
interval = 1
skip = vnet0,vnet1,br0
enabled = yes
```

Thanks in advance!

**Comment by vfuse** [comment]
This is already possible edit `/etc/nixstats.ini` and add `interfaces` to setup the interfaces you want to *enable*.

```
[network]
interval = 1
interfaces = eth0,eth1,eth3...
enabled = yes
```
