### ISSUE TITLE
v1.2.7 throw some errors when upgraded

### ISSUE THREAD

**Issue by mthld** [NIXStats/nixstatsagent#40]
hi,

i just passed v1.2.7 to all our servers and i got the same error on all machines:
```
$ sudo pip3 install nixstatsagent --upgrade
Collecting nixstatsagent
  Downloading https://files.pythonhosted.org/packages/e6/38/1080cc784ec9f791d0bb88caca483e6dffbf4be3828814d0eaa23aabca0e/nixstatsagent-1.2.7.tar.gz
Requirement already satisfied, skipping upgrade: configparser in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (4.0.2)
Requirement already satisfied, skipping upgrade: future in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (0.18.2)
Requirement already satisfied, skipping upgrade: netifaces in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (0.10.9)
Requirement already satisfied, skipping upgrade: psutil in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (5.6.7)
Building wheels for collected packages: nixstatsagent
  Running setup.py bdist_wheel for nixstatsagent ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-brs7ly8c/nixstatsagent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-i4a1j6cm --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for nixstatsagent
  Running setup.py clean for nixstatsagent
Failed to build nixstatsagent
Installing collected packages: nixstatsagent
  Found existing installation: nixstatsagent 1.2.3
    Uninstalling nixstatsagent-1.2.3:
      Successfully uninstalled nixstatsagent-1.2.3
  Running setup.py install for nixstatsagent ... done
Successfully installed nixstatsagent-1.2.7
```

however it doesn't seems to directly impact the agent, after being restarted everything seems to work as intended

**Comment by vfuse** [comment]
What if you install python3-setuptools and python3-wheels? (Apt-get install python3-setuptools python3-wheels)

Kind regards,
Vincent van Megen
On Mon, Mar 2, 2020 at 20:31, mathilde <notifications@github.com> wrote:
hi,

i just passed v1.2.7 to all our servers and i got the same error on all machines:

$ sudo pip3 install nixstatsagent --upgrade
Collecting nixstatsagent
  Downloading https://files.pythonhosted.org/packages/e6/38/1080cc784ec9f791d0bb88caca483e6dffbf4be3828814d0eaa23aabca0e/nixstatsagent-1.2.7.tar.gz
Requirement already satisfied, skipping upgrade: configparser in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (4.0.2)
Requirement already satisfied, skipping upgrade: future in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (0.18.2)
Requirement already satisfied, skipping upgrade: netifaces in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (0.10.9)
Requirement already satisfied, skipping upgrade: psutil in /usr/local/lib/python3.7/dist-packages (from nixstatsagent) (5.6.7)
Building wheels for collected packages: nixstatsagent
  Running setup.py bdist_wheel for nixstatsagent ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-brs7ly8c/nixstatsagent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-i4a1j6cm --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for nixstatsagent
  Running setup.py clean for nixstatsagent
Failed to build nixstatsagent
Installing collected packages: nixstatsagent
  Found existing installation: nixstatsagent 1.2.3
    Uninstalling nixstatsagent-1.2.3:
      Successfully uninstalled nixstatsagent-1.2.3
  Running setup.py install for nixstatsagent ... done
Successfully installed nixstatsagent-1.2.7


however it doesn't seems to directly impact the agent, after being restarted everything seems to work as intended

**Comment by mthld** [comment]
Hi,

Sorry for the delay answering. It seems that dependancies are missing and that installing `python3-setuptools` and `python3-wheel` correct the issue.
